apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-consumer-1
  namespace: demo
spec:
    template:
      spec:
        containers:
          - name: consumer
            image: obaydullahmhs/kafka-consumer:dev
            imagePullPolicy: Always
            env:
              - name: KAFKA_BROKERS
                value: kafka-prod-broker-0.kafka-prod-pods.demo.svc.cluster.local:9092,kafka-prod-broker-1.kafka-prod-pods.demo.svc.cluster.local:9092
              - name: KAFKA_TOPIC
                value: migration
              - name: KAFKA_CONSUMER_GROUP
                value: group-migration-1
        restartPolicy: Never
    backoffLimit: 4
---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: kafka-consumer-2
#   namespace: demo
# spec:
#     template:
#       spec:
#         containers:
#           - name: consumer
#             image: obaydullahmhs/kafka-consumer:dev
#             imagePullPolicy: Always
#             env:
#               - name: KAFKA_BROKERS
#                 value: kafka-prod-broker-0.kafka-prod-pods.demo.svc.cluster.local:9092,kafka-prod-broker-1.kafka-prod-pods.demo.svc.cluster.local:9092              
#               - name: KAFKA_TOPIC
#                 value: migration
#               - name: KAFKA_CONSUMER_GROUP
#                 value: group-migration-2
#         restartPolicy: Never
#     backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-consumer-3
  namespace: demo
spec:
    template:
      spec:
        containers:
          - name: consumer
            image: obaydullahmhs/kafka-consumer:dev
            imagePullPolicy: Always
            env:
              - name: KAFKA_BROKERS
                value: kafka-prod-broker-0.kafka-prod-pods.demo.svc.cluster.local:9092,kafka-prod-broker-1.kafka-prod-pods.demo.svc.cluster.local:9092
              - name: KAFKA_TOPIC
                value: test
              - name: KAFKA_CONSUMER_GROUP
                value: group-test-1
        restartPolicy: Never
    backoffLimit: 4

